### ISSUE TITLE
not able to share folders

### ISSUE THREAD

**Issue by CordlessWool** [nextcloud/files_downloadactivity#10]
### Steps to reproduce
1. share a folder by link with password
2. try to open it on an other pc
3. no files shown in the folder (share folder with other members is no problem, also sharing files. Enter the site with the password are also possible)

### Expected behaviour
The files in the folder should be shown. 

### Actual behaviour
no files are shown

### Server configuration
**Operating system**: Docker container 11.0.1-fpm on Debian 8.6

**Web server:** 

**Database:**

**PHP version:** 5.6

**Nextcloud version:** (see Nextcloud admin page)
11.0.1

**Where did you install Nextcloud from:**

**Signing status:**

No errors have been found.

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:** Firefox/Safarie

**Operating system:**
Linux, Mac
#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by nickvergessen** [comment]
Are you sure there is nothing in your nextcloud.log file?

**Comment by derekblankmccoy** [comment]
AFAIK, this app is for local shares, not sharing via link.

**Comment by nickvergessen** [comment]
Yeah, right. Link shares are dealt with by the "File sharing" app.
There was also an issue which prevented the activities in some cases.
So maybe you can retest it with Nextcloud 11.0.2
If the issue still exists, create a new issue in the server repository.
