### ISSUE TITLE
New feature request: Activities of all users for admins

### ISSUE THREAD

**Issue by Gallindko** [nextcloud/files_downloadactivity#105]
Please integrate this app :
https://apps.nextcloud.com/apps/files_trackdownloads
This repository will not be maintained by me anymore, because I don't need this plugin anymore. Feel free to fork it. Transfering ownership of the repository might also be an option.

Thanks

**Comment by nickvergessen** [comment]
For me there's a huge difference in regards to privacy, so i will not merge them. But I'm also willing to gift the app is someone wants to maintain it, otherwise i can keep the current maintenance work going and release it every time

**Comment by Gallindko** [comment]
OK, I understand. Thank You for your answer.
I wish You best of luck and health.
