### ISSUE TITLE
Bundle notifications in Activity View

### ISSUE THREAD

**Issue by jGleitz** [nextcloud/files_downloadactivity#11]
(Not a bug, so I’m not using the template)

Other sources can bundle activities in the Activity view (`https://[url]/apps/activity/`), which then reads approximately like

> x.pdf, y.pdf, z.pdf and 5 others were created by [user]

 It would be very helpful if this app could do this to.

## 1. Use case: Bundle by user

Right now, if a user downloads `n` files (like all 50 images in a folder), you get `n` entries in the activity view. This could be condensed to only one entry, which would make the view a lot less noisy. Such an entry would look like this:

> x.pdf, y.pdf, z.pdf and 5 others were downloaded by [user] via the web interface

## 2. Use case: Bundle by file

If a new file is created, it is downloaded by all users having the sync client installed. For `n` such users, you have `n` entries. I don’t know if that’s possible, but it would be great to have only one entry, like

> x.pdf was was downloaded by user a, user b, user c and 3 others via the destop client

this would again make the view a lot less noisy.

## More bundling

Of course, both bundling techniques could be combined in some cases, but I picture this would be a lot more complicated to get right. If the two strategies above would be applied, this would already significantly improve the activity view’s clarity

**Comment by nickvergessen** [comment]
Yes, makes a lot of sense

**Comment by jGleitz** [comment]
Thanks a lot for the fast implementation! :+1:
