### ISSUE TITLE
Support Nextcloud 27

### ISSUE THREAD

**Issue by tcarrondo** [nextcloud/files_downloadactivity#148]
Nextcloud 27.0.0 has been released. Please let us know what's required to support it so we can help and when we might expect a release.

**Comment by D1StrX** [comment]
I just figured out that this app is default functionality on NC 27 (seen here for the first time by me).
Administration settings -> Activity -> Files. The NC activity in the Desktop app (seen on windows) shows the shared/download updates there as well.

**Comment by ostasevych** [comment]
> I just figured out that this app is default functionality on NC 27 (seen here for the first time by me). Administration settings -> Activity -> Files. The NC activity in the Desktop app (seen on windows) shows the shared/download updates there as well.

So, does this mean, that is is easily possible to remove this app from installed ones when using NC 27 and upper?
