### ISSUE TITLE
Issues with Nextcloud 28

### ISSUE THREAD

**Issue by martinhechenberger** [nextcloud/files_downloadactivity#159]
### Steps to reproduce
1. Install and Activate App
2. Share File
3. Observe Logging

### Expected behaviour
If push and/or share action is configured, you should get a popup and/or email notifications. 

### Actual behaviour
No push notifications appear and no email notification is sent. Logfile is flooded with the lines below.

### Server configuration

**Operating system**:
Ubuntu 22.04
**Web server:**
Server version: Apache/2.4.52 (Ubuntu)
Server built:   2023-10-26T13:44:44
**Database:**
MariaDB 10.6.12-0ubuntu0.22.04.1
**PHP version:**
PHP 8.1.2-1ubuntu2.14
**Nextcloud version:** (see Nextcloud admin page)
28.0.0
**Where did you install Nextcloud from:**
Nexctloud download repository
**Signing status:**
No errors have been found.
**List of activated apps:**
  - activity: 2.20.0
  - circles: 28.0.0-dev
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contactsinteraction: 1.9.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - firstrunwizard: 2.17.0
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - nextcloud_announcements: 1.17.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - related_resources: 1.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.0
  - sharebymail: 1.18.0
  - support: 1.11.0
  - survey_client: 1.16.0
  - systemtags: 1.18.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_admin: 4.4.0
  - twofactor_backupcodes: 1.17.0
  - twofactor_email: 2.7.4
  - twofactor_gateway: 0.20.0
  - twofactor_totp: 10.0.0-beta.2
  - updatenotification: 1.18.0
  - user_ldap: 1.19.0
  - viewer: 2.2.0
  - workflowengine: 2.10.0
Disabled:
  - admin_audit: 1.18.0
  - bruteforcesettings: 2.8.0
  - dashboard: 7.8.0 (installed 7.8.0)
  - encryption: 2.16.0
  - files_downloadactivity: 1.16.0 (installed 1.16.0)
  - files_external: 1.20.0
  - photos: 2.4.0 (installed 2.4.0)
  - recommendations: 2.0.0 (installed 2.0.0)
  - suspicious_login: 6.0.0
  - user_status: 1.8.1 (installed 1.8.1)
  - weather_status: 1.8.0 (installed 1.8.0)
**Nextcloud configuration:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.we-tirol.at"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.0.11",
        "overwrite.cli.url": "https:\/\/cloud.we-tirol.at",
        "htaccess.RewriteBase": "\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "sendmail",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "app.mail.verify-tls-peer": false,
        "tempdirectory": "\/tmp\/nextcloudtemp",
        "app_install_overwrite": [
            "twofactor_gateway",
            "openotp_auth",
            "apporder",
            "files_downloadactivity"
        ],
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "log_type": "file",
        "logfile": "nextcloud.log",
        "loglevel": 3,
        "logdateformat": "F d, Y H:i:s",
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "default_phone_region": "AT",
        "default_language": "de",
        "default_locale": "de_AT",
        "skeletondirectory": "\/var\/nextcloud_defaultfiles",
        "share_folder": "\/Mit mir geteilt",
        "defaultapp": ""
    }
}

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP
### Client configuration
**Browser:**
Firefox 120.0
**Operating system:**
Windows 11 Version 22H2
#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here
Repeatedly:
{"reqId":"xtmpluEVBSWQMMK86UHe","level":4,"time":"December 15, 2023 09:55:01","remoteAddr":"","user":"--","app":"no app in context","method":"","url":"--","message":"Could not boot files_downloadactivity: Call to undefined method OC\\Server::getEventDispatcher()","userAgent":"--","version":"28.0.0.11","exception":{"Exception":"Error","Message":"Call to undefined method OC\\Server::getEventDispatcher()","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php","line":200,"function":"boot","class":"OCA\\FilesDownloadActivity\\AppInfo\\Application","type":"->"},{"file":"/var/www/nextcloud/lib/private/App/AppManager.php","line":434,"function":"bootApp","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->"},{"file":"/var/www/nextcloud/lib/private/App/AppManager.php","line":213,"function":"loadApp","class":"OC\\App\\AppManager","type":"->"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_App.php","line":125,"function":"loadApps","class":"OC\\App\\AppManager","type":"->"},{"file":"/var/www/nextcloud/cron.php","line":55,"function":"loadApps","class":"OC_App","type":"::"}],"File":"/var/www/nextcloud/apps/files_downloadactivity/lib/AppInfo/Application.php","Line":49,"message":"Could not boot files_downloadactivity: Call to undefined method OC\\Server::getEventDispatcher()","exception":{},"CustomMessage":"Could not boot files_downloadactivity: Call to undefined method OC\\Server::getEventDispatcher()"}}

**Comment by skjnldsv** [comment]
Fixed in upcoming release
