### ISSUE TITLE
Track All Download Events and Group Events for Users That are not Logged In

### ISSUE THREAD

**Issue by elisman** [nextcloud/files_downloadactivity#16]
(Not a bug, so I am not using the template)

Download activities by users that are not logged in are not tracked.

### Track all download events and group events for users that are not logged in

In my opionion it would be better to track all download events. This way statistics about download activities would be more accurate. As no information is available about anonymous users, it would be sufficient to track the event, file and timestamp.

In the code there is a comment that some other app would track this, but in my opinion it should be tracked all in the same app.

**Comment by nickvergessen** [comment]
Public link and share by mail downloads are already handled by the sharing app.
Not sure if we really should duplicate those?!

**Comment by elisman** [comment]
My mistake. I just missed the anonymous download activities in the panel. They are tracked as you state. Sorry for the inconvenience.
