### ISSUE TITLE
When will Nextcloud 27 and 28, 29 and 30 support be added?

### ISSUE THREAD

**Issue by arno4000** [nextcloud/files_downloadactivity#165]
### Steps to reproduce
1. Install the app on Nextcloud 27
2. Get the message `Error: This app cannot be enabled because it makes the server unstable` when enabling the app. When the app is enabled via `occ app:enable files_downloadactivity`, there is no error message.

### Expected behaviour
The app should work on Nextcloud versions, which are not EOL in two months.
### Actual behaviour
The app does not work in Nextcloud Versions which are newer than 26

**Comment by Sblop** [comment]
+1

**Comment by BloodyIron** [comment]
Can we please get this just mainlined into nextCloud already? This really should be core functionality by default. Tracking activity across large nextCloud instances requires things like this.

**Comment by arno4000** [comment]
FYI: It works on NC 27 if you increase the max version in the info.xml of the app. But this is a hacky workaround which can potentially break at any time. It would be nice if the app would be updated before a new version of nextcloud is released.

**Comment by immanuelfodor** [comment]
There was probably a change in NC as well as my logs are splattered everywhere with `"message":"Could not boot files_downloadactivity: Call to undefined method OC\\Server::getEventDispatcher()"`

**Comment by WechuTM** [comment]
This file modification enables the application to be used on NC 28.0.3 RC1

**Comment by WechuTM** [comment]
> > There was probably a change in NC as well as my logs are splattered everywhere with `"message":"Could not boot files_downloadactivity: Call to undefined method OC\\Server::getEventDispatcher()"`
> 
> Also reporting this, thousands of lines per day.

Make the modifications described in the post https://github.com/christian-baumann/files_downloadactivity/commit/a5f5f7a4fd101258da8563111c349ed3679162ce should remove the error

**Comment by nooblag** [comment]
Thanks for that. I'd prefer an update released though, not too comfortable modifying files. Also, it'd be great if this app was made redundant anyways by mainlining like @BloodyIron suggested :) Would love that

**Comment by sephentos** [comment]
Title should be updated to include NC 29.0.0 :P

**Comment by skjnldsv** [comment]
For everyone, the app needs to be updated, sure, but you can force enable it.
It works just fine :see_no_evil:

**Comment by skjnldsv** [comment]
Only the `Call to undefined method OC\\Server::getEventDispatcher()`  :eyes:

**Comment by skjnldsv** [comment]
Fixed in upcoming release

**Comment by BloodyIron** [comment]
Yay! But will this ever be mainlined?
