### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by jGleitz** [nextcloud/files_downloadactivity#17]
I have manually overridden `lib/Activity/Provider.php` by the version from fc0f984b76c863b3006c31b9656ee735ab38fbea to profit from #12 . Because of that, the code integrity check fails.

I think it’d be desirable to publish a new version to make all users profit from the new functionality (and fix my code integration issue).

**Comment by nickvergessen** [comment]
Yeah I wanted to wait until 12 beta is out, but  then I got sick last week.

**Comment by nickvergessen** [comment]
https://apps.nextcloud.com/apps/files_downloadactivity
https://github.com/nextcloud/files_downloadactivity/releases/tag/v1.1.1
