### ISSUE TITLE
Question: how is this app different from **Activity** ?

### ISSUE THREAD

**Issue by dachary** [nextcloud/files_downloadactivity#32]
The official **Activity** app that comes with 13.0.1 has a setting that does the same, and activity shows dowloads. 

![a](https://user-images.githubusercontent.com/433594/38865681-d5f6dfa2-423e-11e8-86ce-dc8ef32599a8.png)

What does **files_downloadactivity** do that **Activity** does not?

![enabled](https://user-images.githubusercontent.com/433594/38865626-a1776fbc-423e-11e8-870c-a14d70cd0c07.png)

**Comment by nickvergessen** [comment]
This app here tracks user downloads, while the base functionality in the activity app only tracks downloads of public links.
It was separated, because user downloads also happen via the sync client, so it can spam a lot.
