### ISSUE TITLE
Non-user downloads IP address stats

### ISSUE THREAD

**Issue by NuxRo** [nextcloud/files_downloadactivity#41]
Hello,
I see there is already a patch for this feature, but you have refused the PR due to GDPR.
Can I argue that the GDPR responsability lies with the user of the software and not the manufacturer?
Can you please give this another thought and incorporate functionality?
The IPs would already be in all sorts of DBs and logs anyway, think Apache httpd and so on.

**Comment by nickvergessen** [comment]
I will not implement this, but I'm open to handing over the maintainership of this app to someone else. My usecase for this app also vanished, which is why there was no further feature development in the last year.

**Comment by nickvergessen** [comment]
Actually let me close this one in favor of #30
