### ISSUE TITLE
Repeating entries in download activity for a single download

### ISSUE THREAD

**Issue by TeslaBenny** [nextcloud/files_downloadactivity#49]
### Steps to reproduce
1. Share file to a group and public link
2. File is accessed by group member via browser or app, or file is accessed via public link
3. View Activity feed stream or activity on file showing 4+ instances for a single download request

### Expected behaviour
Expecting to see only 1 entry on Activity feed per download request

### Actual behaviour
Seeing 4+ (sometimes 8, 9, or even 10) entries on Activity feed per download request

## Server configuration detail

**Operating system:** Linux 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64

**Webserver:** Apache/2.4.29 (Ubuntu) (fpm-fcgi)

**Database:** mysql 10.1.41

**PHP version:** 

7.2.19-0ubuntu0.18.04.2
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, apc, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, intl, json, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 16.0.5 - 16.0.5.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 15.x Nextcloud

**Where did you install Nextcloud from:** Installer from nextcloud.com

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.2.0
 - activity: 2.9.1
 - announcementcenter: 3.5.1
 - calendar: 1.7.1
 - cloud_federation_api: 0.2.0
 - cms_pico: 0.9.8
 - comments: 1.6.0
 - contacts: 3.1.6
 - dav: 1.9.2
 - event_update_notification: 0.3.4
 - federatedfilesharing: 1.6.0
 - federation: 1.6.0
 - files: 1.11.0
 - files_downloadactivity: 1.5.0
 - files_fulltextsearch: 1.3.6
 - files_markdown: 2.1.0
 - files_pdfviewer: 1.5.0
 - files_rightclick: 0.15.1
 - files_sharing: 1.8.0
 - files_texteditor: 2.8.0
 - files_trackdownloads: 1.5.0
 - files_trashbin: 1.6.0
 - files_versions: 1.9.0
 - files_videoplayer: 1.5.0
 - firstrunwizard: 2.5.0
 - fulltextsearch: 1.3.6
 - fulltextsearch_elasticsearch: 1.3.6
 - gallery: 18.3.0
 - guests: 1.2.2
 - impersonate: 1.3.0
 - issuetemplate: 0.5.0
 - keeweb: 0.5.1
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - metadata: 0.10.0
 - music: 0.10.1
 - nextcloud_announcements: 1.5.0
 - notes: 3.0.3
 - notifications: 2.4.1
 - oauth2: 1.4.2
 - password_policy: 1.6.0
 - previewgenerator: 2.1.0
 - privacy: 1.0.0
 - provisioning_api: 1.6.0
 - ransomware_protection: 1.4.0
 - recommendations: 0.4.0
 - serverinfo: 1.6.0
 - sharebymail: 1.6.0
 - spreed: 6.0.4
 - support: 1.0.0
 - survey_client: 1.4.0
 - systemtags: 1.6.0
 - tasks: 0.11.3
 - text: 1.0.2
 - theming: 1.7.0
 - twofactor_backupcodes: 1.5.0
 - twofactor_nextcloud_notification: 1.1.2
 - twofactor_totp: 3.0.1
 - updatenotification: 1.6.0
 - viewer: 1.1.0
 - workflowengine: 1.6.0
Disabled:
 - admin_audit
 - encryption
 - files_antivirus
 - files_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***",
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "16.0.5.1",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "htaccess.RewriteBase": "\/",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0
    },
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "tempdirectory": "\/mnt\/md0\/nextcloud\/tmp",
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "ssl",
    "mail_sendmailmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "twofactor_enforced": "true",
    "twofactor_enforced_groups": [
        "admin"
    ],
    "twofactor_enforced_excluded_groups": [],
    "mysql.utf8mb4": true,
    "updater.release.channel": "stable",
    "enable_previews": true,
    "preview_max_x": 800,
    "preview_max_y": 800,
    "preview_max_scale_factor": 2.5
}
```
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** No

## Client configuration

**Browser:** Various

**Operating system:** Various

## Logs

<details><summary>Web server error log</summary>

```

```
</details>

<details><summary>Nextcloud log</summary>

```

```
</details>

<details><summary>Browser log</summary>

</details>

**Comment by TeslaBenny** [comment]
Here is an example where the file is downloaded **once** by three different users using three different download methods (public link, browser, and app):
![image](https://user-images.githubusercontent.com/42008752/66541077-43f73780-eaeb-11e9-9401-64666c672cd3.png)

The public link entry repeated 4 times total (screenshot shows first 3 repeats of the 4), the user via browser entry repeated 8 times total, and the user via mobile app entry repeated 10 times total (screenshot shows last 3 repeats of the 10).

**Comment by nickvergessen** [comment]
Do you have a video player app installed?

**Comment by simonspa** [comment]
I posted the same issue here #47 where it was the audio player. I think it happens when users start/stop or jump in the stream - every time a new activity is logged.

**Comment by TeslaBenny** [comment]
Not all of the users were stopping the video player or jumping to different positions within the video. It seems to generate a minimum of 4 entries if the video is just played once all the way through.

@nickvergessen Why was this issue closed? What is the technical cause, and what is the resolution?

**Comment by nickvergessen** [comment]
It's the same issue as the other one linked above. A solution will fix both at the same time, so no need to have 2 issues

**Comment by TeslaBenny** [comment]
Great, thanks! I'm sorry I didn't understand that they are the same issue.
