### ISSUE TITLE
Backends provided no user object for

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/files_downloadactivity#53]
in practice, those who receive the federated folder from another nextcloud despite having the permissions to delete, cannot delete files that only the one who shared the federated folder puts in that folder, while I, who received the shared folder in my nextcloud, can only files but don't delete them as well if other has given me the permissions.

https://github.com/nextcloud/server/issues/19647

![Immagine](https://user-images.githubusercontent.com/35575744/75372954-9d5cd900-58c9-11ea-8e61-b8d12cea6f76.png)

**Comment by nickvergessen** [comment]
This seems to be about another app, not the download activities?

**Comment by tigernero79** [comment]
@nickvergessen I don't know if it exactly refers to the download but in an old commit you had faced a similar error.  in practice I cannot delete files from a federated folder who shared the federated folder yes, I who received invitation no.  it gives me that error on nextcloud 18. try to be sent a federated test folder you will see you cannot delete files inside your friend instead yes
