### ISSUE TITLE
wrong version included in stable v19 and on appstore

### ISSUE THREAD

**Issue by aignerat** [nextcloud/files_downloadactivity#65]
### Steps to reproduce
1. Try to activate files_downloadactivity

### Expected behaviour
activation of the app

### Actual behaviour
wrong version error

**Nextcloud version:** 19.0.1

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

The app is included in stable19, I installed it on 19.0.1, it should be version 1.9.0 but it is 1.10.0
Appinfo - info.xml shows it's made for v21, even changing this to v19 doesn't make the app work. Seems like 1.9.0 is mapped to the wrong tag. I tried to install 1.8.0 for v18 and change the version-number in info.xml but it didn't work as well.

I try to download the stable19 from github

**Comment by nickvergessen** [comment]
> The app is included in stable19

The app is not included by default.

Also please note that the version number is not linked to the Nextcloud version number, as you can see on https://apps.nextcloud.com/apps/files_downloadactivity : 
1.7.0 is for Nextcloud 18
1.8.0 is for Nextcloud 19
1.9.0 is for Nextcloud 20
