### ISSUE TITLE
Enable Support for Nextcloud 22

### ISSUE THREAD

**Issue by adripo** [nextcloud/files_downloadactivity#76]
Please update for nextcloud version 22.

**Comment by nickvergessen** [comment]
Release is available at https://github.com/nextcloud-releases/files_downloadactivity/releases/download/v1.11.0/files_downloadactivity-1.11.0.tar.gz

Available in the appstore soon

**Comment by maxcco** [comment]
@nickvergessen  just download it, still says it's unsupported on v22
