### ISSUE TITLE
Download reported although user only views file.

### ISSUE THREAD

**Issue by RegisPerdreau** [nextcloud/files_downloadactivity#78]
### Steps to reproduce
1. view a file with Collaborafice, Onlyoffice, built-in editor with no modification
2. check Activity in side bar
3. Download is reported 

### Expected behaviour
download shoudn't be reported

### Actual behaviour
download is reported

with Nextcloud 20.0.11

**Comment by nickvergessen** [comment]
Opening a file and viewing the content is what is reported as downloading, there is also no way to tell that apart.
