### ISSUE TITLE
Make app compatible with NC 23

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/files_downloadactivity#83]
NC23 is out and updater says app is not compatible.

Using NC v22.2.3

**Comment by nickvergessen** [comment]
can you try to update and force enable it and report back if it is working?

**Comment by rakekniven** [comment]
On my productive NC I have too many apps not ready for NC23 and therefore I will not update at the moment.
I can give it a try as soon as main apps are available and report.

**Comment by leonardohlee** [comment]
waiting for it ready for NC 23

**Comment by rakekniven** [comment]
> waiting for it ready for NC 23

@leonardohlee 

Before adding a new comment and causing lot of emails being sent it is better to vote with thumbs up at first comment of issue. Bye.

**Comment by rakekniven** [comment]
Please leave issue open until I reported and the app is ready for NC23.

**Comment by nickvergessen** [comment]
I released the app, it is ready

**Comment by rakekniven** [comment]
Very nice. Thanks.

**Comment by leonardohlee** [comment]
Thanks!
