### ISSUE TITLE
Identificator changed from "Display Name" to "User Name"

### ISSUE THREAD

**Issue by angeloKairos** [nextcloud/files_downloadactivity#85]
### Steps to reproduce
1. A user downloads a file

### Expected behaviour
The activity log contained the users "Display Name".

### Actual behaviour
The activity log contains the "User Name". Maybe this changed in one or another release, but I was unable to find the faeture issue here. Anyhow as we automatically parse for the Display Name in the activity, this is somehow neccessary for us.

### Server configuration

**Operating system**: Linux 4.15.0-135-generic x86_64

**Web server:** hosted -> unknown

**Database:** mysql 8.0.27

**PHP version:** 7.3.33

**Nextcloud version:** 22.2.3

**Where did you install Nextcloud from:** hosted

**Signing status:** unknown

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```
- disabled by hoster -

**List of activated apps:**

- disabled by hoster -

**Nextcloud configuration:**

- disabled by hoster -

**Are you using an external user-backend, if yes which one:** no

**Comment by nickvergessen** [comment]
As per https://github.com/nextcloud/files_downloadactivity/pull/86#discussion_r813030608 this is a problem of the forked app, it works fine in this app here
